### ISSUE TITLE
How to suggest to Apple a new HKHealthStore object inside HealthKit?

### ISSUE THREAD

**Issue by andregoiano** [wellcomez/ios8#1]
Hi @wellcomez, I'm currently looking for the right code syntax in order to suggest to the Apple software team to create a new data object inside iOS8's HealthKit — a boolean that would hold the user's organ donation preferences — before the official launch later this year. I'm not an iOS developer. Would you be able to help me code it properly using Objective C or Swift?

**Comment by wellcomez** [comment]
卖肾吗？

**Comment by wellcomez** [comment]
@property(noautomatic,readwrite)bool organdonate
